//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UshakovAviaSales.DataFD
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightData()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int idFlight { get; set; }
        public int idDestination { get; set; }
        public bool isCanceled { get; set; }
        public int idCompany { get; set; }
        public int FlightTimeDurationInMinutes { get; set; }
        public System.DateTime DateOfFlight { get; set; }
        public string PlaneNumber { get; set; }
        public Nullable<decimal> EconomPrice { get; set; }
        public Nullable<decimal> BuisinessPrice { get; set; }
        public int idDestinationFrom { get; set; }
        public Nullable<System.DateTime> DateFlightEnd { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Destination Destination1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
