//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UshakovAviaSales.DataFD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int idNotification { get; set; }
        public int idClient { get; set; }
        public Nullable<System.DateTime> DateOfNotifying { get; set; }
        public decimal Price { get; set; }
        public string AdditionalInformation { get; set; }
        public int idPriceCheck { get; set; }
        public int HotelId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateSet { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pricecheck Pricecheck { get; set; }
    }
}
