//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UshakovAviaSales.DataFD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int idTicket { get; set; }
        public int idClient { get; set; }
        public int Seat { get; set; }
        public string FlightDescription { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int idTicketType { get; set; }
        public int idFlight { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual FlightData FlightData { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
